# Generated by Django 3.2 on 2021-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_cabeceramodel_detallemodel_productomodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemodel',
            options={'verbose_name': 'detallee'},
        ),
    ]
