# Generated by Django 3.2 on 2021-05-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_detallemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallemodel',
            options={'verbose_name': 'detalle'},
        ),
    ]
